services:
  web:
    container_name: django
    image: dezporcento:latest
    build:
      context: .
    env_file: .env
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: {}
