# Generated by Django 3.1.1 on 2020-09-13 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0016_remove_dizimista_perfil"),
        ("core", "0003_perfil_dizimista"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="dizimista",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao.dizimista",
            ),
        ),
    ]
