# Generated by Django 3.1.1 on 2020-09-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0016_remove_dizimista_perfil"),
        ("core", "0004_auto_20200913_1625"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfil"},
        ),
        migrations.AlterField(
            model_name="perfil",
            name="dizimista",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to="gestao.dizimista",
            ),
        ),
    ]
