# Generated by Django 3.1.1 on 2020-09-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200913_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='dizimista',
        ),
    ]
