# Generated by Django 3.1.1 on 2020-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço')),
                ('nascimento', models.DateField(auto_now=True, null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Dizimista',
                'verbose_name_plural': 'Dizimistas',
            },
        ),
    ]
