# Generated by Django 3.1.1 on 2020-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dizimista',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
    ]
