# Generated by Django 3.1.1 on 2020-09-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20200903_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPagamentos',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório de Pagamentos',
                'verbose_name_plural': 'Relatórios de Pagamentos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestao.pagamento',),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='dizimista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.dizimista'),
        ),
    ]
