# Generated by Django 3.1.1 on 2020-09-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_dizimista_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1),
        ),
    ]
