# Generated by Django 3.1.1 on 2020-09-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestao", "0003_auto_20200904_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="igreja",
            name="agentes",
            field=models.ManyToManyField(
                related_name="_igreja_agentes_+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="igreja",
            name="coordenadores",
            field=models.ManyToManyField(
                related_name="_igreja_coordenadores_+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dizimista",
            name="igreja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao.igreja",
            ),
        ),
    ]
