# Generated by Django 3.1.1 on 2020-09-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_dizimista_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dizimista',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], default='M', max_length=1),
        ),
    ]
