# Generated by Django 3.1.1 on 2020-09-07 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestao", "0005_auto_20200906_1725"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="igreja",
            name="coordenadores",
        ),
        migrations.AddField(
            model_name="igreja",
            name="gestores",
            field=models.ManyToManyField(
                related_name="gestor_em", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
