# Generated by Django 3.1.1 on 2020-09-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_auto_20200902_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.AddField(
            model_name='dizimista',
            name='igreja',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.igreja', verbose_name='Igreja'),
        ),
    ]
