# Generated by Django 3.1.1 on 2020-09-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0007_auto_20200907_2009"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagamento",
            options={"verbose_name": "Pagamento", "verbose_name_plural": "Pagamentos"},
        ),
    ]
