# Generated by Django 3.1.1 on 2020-09-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_auto_20200902_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dizimista',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.RemoveField(
            model_name='dizimista',
            name='igreja',
        ),
        migrations.AddField(
            model_name='dizimista',
            name='igrejas',
            field=models.ManyToManyField(to='gestao.Igreja', verbose_name='Igrejas'),
        ),
    ]
