# Generated by Django 3.1.1 on 2020-09-02 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_auto_20200902_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dizimista',
            options={'verbose_name': 'Dizimista', 'verbose_name_plural': 'Dizimistas'},
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2020, 9, 2, 20, 55, 4, 627622, tzinfo=utc), verbose_name='Data e hora')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('dizimista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.dizimista', verbose_name='Dizimista')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.igreja', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
