# Generated by Django 3.1.1 on 2020-09-02 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_auto_20200902_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 20, 55, 38, 536905, tzinfo=utc), verbose_name='Data e hora'),
        ),
    ]
