# Generated by Django 3.1.1 on 2020-09-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0009_auto_20200908_0101"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResumoDiarios",
        ),
        migrations.CreateModel(
            name="ResumoMenal",
            fields=[],
            options={
                "verbose_name": "Resumo Mensal",
                "verbose_name_plural": "Resumos Mensais",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gestao.pagamento",),
        ),
    ]
