# Generated by Django 3.1.1 on 2020-09-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0011_auto_20200908_0104"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagamento",
            options={
                "ordering": ["-data"],
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
    ]
