# Generated by Django 3.1.1 on 2020-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0012_auto_20200908_0118"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResumoMensal",
        ),
        migrations.CreateModel(
            name="ResumoPagamentos",
            fields=[],
            options={
                "verbose_name": "Resumo de pagamentos",
                "verbose_name_plural": "Resumos de pagamentos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gestao.pagamento",),
        ),
        migrations.AlterField(
            model_name="dizimista",
            name="genero",
            field=models.CharField(
                choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                default="F",
                max_length=1,
                verbose_name="Gênero",
            ),
        ),
    ]
