# Generated by Django 3.1.1 on 2020-09-02 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_auto_20200902_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dizimista',
            name='igrejas',
        ),
        migrations.AddField(
            model_name='dizimista',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.igreja', verbose_name='Igrejas'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 21, 7, 40, 913515, tzinfo=utc), verbose_name='Data e hora'),
        ),
    ]
