# Generated by Django 3.1.1 on 2020-09-02 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_auto_20200902_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 21, 12, 7, 327751, tzinfo=utc), verbose_name='Data e hora'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
