# Generated by Django 3.1.1 on 2020-09-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20200913_1022"),
        ("gestao", "0013_auto_20200910_1305"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dizimista",
            name="email",
        ),
        migrations.RemoveField(
            model_name="dizimista",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="dizimista",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="dizimista",
            name="nascimento",
        ),
        migrations.RemoveField(
            model_name="dizimista",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="dizimista",
            name="telefone",
        ),
        migrations.AddField(
            model_name="dizimista",
            name="perfil",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perfil",
                verbose_name="Perfil",
            ),
        ),
    ]
