# Generated by Django 3.1.1 on 2020-09-02 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_auto_20200902_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 21, 14, 19, 459294, tzinfo=utc), verbose_name='Data e hora'),
        ),
    ]
