# Generated by Django 3.1.1 on 2020-09-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_auto_20200913_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dizimista',
            name='perfil',
        ),
    ]
