# Generated by Django 3.1.1 on 2020-09-02 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_auto_20200902_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 21, 30, 54, 472318, tzinfo=utc), verbose_name='Data e hora'),
        ),
    ]
