# Generated by Django 3.1.1 on 2020-09-02 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_auto_20200902_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dizimista',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.igreja'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 21, 37, 18, 92909, tzinfo=utc), verbose_name='Data e hora'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='dizimista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.dizimista'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.igreja'),
        ),
    ]
