# Generated by Django 3.1.1 on 2020-09-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_perfil_dizimista"),
        ("gestao", "0018_dizimista_dizimo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dizimista",
            name="perfil",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dizimista",
                to="core.perfil",
            ),
        ),
    ]
