# Generated by Django 3.1.1 on 2020-09-02 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0019_auto_20200902_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestao.igreja'),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 22, 56, 0, 807828, tzinfo=utc), verbose_name='Data e hora'),
        ),
    ]
