# Generated by Django 3.1.1 on 2020-09-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0020_auto_20200914_1052"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dizimista",
            name="perfil",
        ),
        migrations.AddField(
            model_name="perfildizimista",
            name="dizimista",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao.dizimista",
            ),
        ),
    ]
