# Generated by Django 3.1.1 on 2020-09-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0021_auto_20200914_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfildizimista",
            name="dizimista",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to="gestao.dizimista",
            ),
        ),
    ]
