# Generated by Django 3.1.1 on 2020-09-03 01:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0021_auto_20200903_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 1, 28, 4, 893502, tzinfo=utc), verbose_name='Data e hora'),
        ),
    ]
