# Generated by Django 3.1.1 on 2020-09-03 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0022_auto_20200903_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora'),
        ),
    ]
